credentials:
  usernames:
    jeevan:
      email: jeevan@example.com
      name: Jeevan
      password: '$2b$12$M/sA8okAnZHGKcX3QTa1g.MQfBu95m9lkhxBQHq7hkEJNZztko3ne'
    admin:
      email: admin@example.com
      name: Admin
      password: '$2b$12$KbIbw2YqvM.c2y9G3p8pYu9vyO4bO/D.oRo.UsG8bGYNc3kMo.7ve'

cookie:
  name: stackup_session
  key: abc123_secret_key
  expiry_days: 1