credentials:
  usernames:
    jeevan:
      email: jeevan@example.com
      name: Jeevan
      password: "$2b$12$qXnrU6jNBfjW6VUJYKinNOQkw.nChAqhgkwttmx7kN0OgRQUtk49S"
    admin:
      email: admin@example.com
      name: Admin
      password: "$2b$12$gMJC./x23ZHAKbJkmpPIJ.Zv3MGv.TZ/iMX3wlU6hwuf.2IlZj5t6"

cookie:
  name: stackup_session
  key: abc123_secret_key
  expiry_days: 1