credentials:
  usernames:
    jeevan:
      email: jeevan@example.com
      name: Jeevan
      password: "$2b$12$UJ8JDbKh8eoQwOCa.NAzAeQ1l8SKYTdCOT/42sH4QIsezLnB9/Hnq"
    admin:
      email: admin@example.com
      name: Admin
      password: "$2b$12$J9cjNGKfpaiu7vqxqSmaA.Ukdsi1DWTZaPKx2Y7K65VqHlp9LTgTK"

cookie:
  name: stackup_session
  key: abc123_secret_key
  expiry_days: 1