credentials:
  usernames:
    jeevan:
      email: jeevan@example.com
      name: Jeevan
      password: "$2b$12$u8WxjpIB5G5pGtNCRh6N2ujDNWtL12oCehLJWo9kTjFXIQ8OK4qvm"  # from above
    admin:
      email: admin@example.com
      name: Admin
      password: "$2b$12$CNCh8wtPc66NLL18NLFCc.cSLUKPhuJHmqfviOkJmDfT7xSr6dtNq"

cookie:
  name: stackup_session
  key: abc123_secret_key
  expiry_days: 1